### ISSUE TITLE
Interface crashed when closing luci.js

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#1000]
When closing luci.js the Interface crashes. This is on 2020.3.3 on Linux Mint 19.3.
Backtrace:
```
(gdb) bt
#0  0x00007fffea949928 in QTJSC::ExecState::thisValue (this=0x7ffe00dec108) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/interpreter/CallFrame.cpp:36
#1  0x00007fffeaa86231 in QScriptEnginePrivate::evaluateHelper (this=this@entry=0x555573f43200, exec=exec@entry=0x7ffe00dec108, sourceId=sourceId@entry=140726846844096, executable=executable@entry=0x7ffddc0ebb00, compile=@0x7ffdffd3c6a8: true) at /home/nissim/qt5/qtscript/src/script/api/qscriptengine.cpp:1383
#2  0x00007fffeaa87589 in QScriptEngine::evaluate (this=<optimized out>, program=..., fileName=..., lineNumber=1) at /home/nissim/qt5/qtscript/src/script/api/qscriptengine.cpp:2723
#3  0x00007fffeacee9c7 in vec2ToScriptValue (engine=0x5555758384e0, vec2=...) at /home/motofckr9k/Vircadia/source/libraries/shared/src/RegisteredMetaTypes.cpp:82
#4  0x00007fffeaa87e85 in QScriptEnginePrivate::create (exec=exec@entry=0x7ffe00dec108, type=<optimized out>, ptr=ptr@entry=0x7ffdb4009900) at /home/nissim/qt5/qtscript/src/script/api/qscriptengine.cpp:3081
#5  0x00007fffeaaad9fe in QScriptEnginePrivate::jscValueFromVariant (v=..., exec=0x7ffe00dec108) at /home/nissim/qt5/qtscript/src/script/bridge/../api/qscriptengine_p.h:652
#6  QScript::QtPropertyFunction::execute (this=<optimized out>, exec=0x7ffe00dec108, thisValue=..., args=...) at /home/nissim/qt5/qtscript/src/script/bridge/qscriptqobject.cpp:1109
#7  0x00007fffea9be028 in QTJSC::NativeFuncWrapper::operator() (this=this@entry=0x7ffdffd3c910, exec=exec@entry=0x7ffe00dec108, jsobj=0x7ffe10090fc0, thisValue=..., argList=...) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/CallData.cpp:46
#8  0x00007fffeaa1dc70 in QTJSC::PropertySlot::functionGetter (exec=0x7ffe00dec108, slot=...) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/PropertySlot.cpp:38
#9  0x00007fffea9ff1fc in QTJSC::PropertySlot::getValue (propertyName=..., exec=<optimized out>, this=0x7ffdffd3c9c0) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/PropertySlot.h:62
#10 QTJSC::Stringifier::Holder::appendNextProperty (this=<optimized out>, stringifier=..., builder=...) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/JSONObject.cpp:559
#11 0x00007fffea9fe3f2 in QTJSC::Stringifier::appendStringifiedValue (this=this@entry=0x7ffdffd3cc60, builder=..., value=..., value@entry=..., holder=holder@entry=0x7ffe10090e80, propertyName=...) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/JSONObject.cpp:440
#12 0x00007fffea9fe757 in QTJSC::Stringifier::stringify (this=this@entry=0x7ffdffd3cc60, value=value@entry=...) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/JSONObject.cpp:266
#13 0x00007fffea9fee0d in QTJSC::JSONProtoFuncStringify (exec=<optimized out>, args=...) at /home/nissim/qt5/qtscript/src/3rdparty/javascriptcore/JavaScriptCore/runtime/JSONObject.cpp:875
#14 0x00007ffefc0141b4 in ?? ()
#15 0x00007ffe00dec0c0 in ?? ()
#16 0x0000000000000001 in ?? ()
#17 0x00007ffe0335a9c0 in ?? ()
#18 0x00007ffe10087980 in ?? ()
#19 0x00007ffefc61869d in ?? ()
#20 0x00007fff00000002 in ?? ()
#21 0x00007ffdffd3cfa0 in ?? ()
#22 0x00007ffe03304cd0 in ?? ()
#23 0x00007ffdfd34b600 in ?? ()
#24 0x0000000000000000 in ?? ()
(gdb) 
```

**Comment by daleglass** [comment]
Dev meeting: I'll try to get a better backtrace

**Comment by JulianGro** [comment]
:angry:

**Comment by daleglass** [comment]
Still needs more info, and given PR #1200 this might be fixed by scripting engine replacement/changes, so it probably should be looked at again after that

**Comment by daleglass** [comment]
Also doesn't happen reliably according to people trying to reproduce it
