### ISSUE TITLE
Building jsdoc fails on v2021.1.2-rc

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#1228]
```
Building target jsdoc
Scanning dependencies of target jsdoc
generate the JSDoc JSON
WARN engine jsdoc@3.6.7: wanted: {"node":">=8.15.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm WARN deprecated axios@0.18.1: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
WARN engine catharsis@0.9.0: wanted: {"node":">= 10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine mkdirp@1.0.4: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine marked@2.0.5: wanted: {"node":">= 8.16.2"} (current: {"node":"8.10.0","npm":"3.5.2"})
npm ERR! Linux 5.4.0-70-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "--no-progress" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/motofckr9k/Vircadia/source/tools/jsdoc/npm-debug.log
tools/jsdoc/CMakeFiles/jsdoc.dir/build.make:57: recipe for target 'jsdoc' failed
make[3]: *** [jsdoc] Error 1
CMakeFiles/Makefile2:6753: recipe for target 'tools/jsdoc/CMakeFiles/jsdoc.dir/all' failed
make[2]: *** [tools/jsdoc/CMakeFiles/jsdoc.dir/all] Error 2
CMakeFiles/Makefile2:6760: recipe for target 'tools/jsdoc/CMakeFiles/jsdoc.dir/rule' failed
make[1]: *** [tools/jsdoc/CMakeFiles/jsdoc.dir/rule] Error 2
Makefile:1811: recipe for target 'jsdoc' failed
make: *** [jsdoc] Error 2
```

Full vircadia-builder log: https://gist.github.com/JulianGro/f97059abfa6740ea872c22ab6b43e85d
npm-debug.log: https://gist.github.com/JulianGro/db7481fef7c83f5910e1a9e3589ab08c

I am busy right now so I have not taken a look at it yet.

**Comment by JulianGro** [comment]
Apparently upgrading NPM is needed for jsdoc to build now.
```
npm install -g npm@5.1.0
```
Upgrading to latest failes, so I just randomly took 5.1.0 which worked.

**Comment by daleglass** [comment]
Which distro are you building this on? Might as well be not a bug, if the local version is too old to work.

**Comment by JulianGro** [comment]
This is on Ubuntu 18.04.
I don't really see what would have changed to make the old NPM version unusable, but the problem is that it doesn't just tell you to update NPM. It should just have a minimum version requirement like CMake and all the other stuff.

**Comment by daleglass** [comment]
Fairly recent changes to the build process should result in NPM no longer being required
