### ISSUE TITLE
Crash in GLTF serializer

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#1542]
When joining Domain "Pushkin2" Interface crashes semi reliable. `gdb` points to the GLTF serializer.
`gdb` says: 
```
Thread 41 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Wechseln zu Thread 0x7ffeae3dd700 (LWP 27958)]
0x00007ffff3406fd5 in GLTFSerializer::buildGeometry (this=this@entry=0x7ffe8cfe7790, hfmModel=..., mapping=..., url=...) at /home/motofckr9k/Vircadia/source/libraries/model-serializers/src/GLTFSerializer.cpp:1261
1261	                        glm::vec3 v3 = glm::vec3(vertices[v3_index], vertices[v3_index + 1], vertices[v3_index + 2]);
```
Backtrace:
```
(gdb) bt
#0  0x00007ffff3406fd5 in GLTFSerializer::buildGeometry (this=this@entry=0x7ffe8cfe7790, hfmModel=..., mapping=..., url=...) at /home/motofckr9k/Vircadia/source/libraries/model-serializers/src/GLTFSerializer.cpp:1261
#1  0x00007ffff340f1f5 in GLTFSerializer::read (this=0x7ffe8cfe7790, data=..., mapping=..., url=...) at /home/motofckr9k/Vircadia/source/libraries/model-serializers/src/GLTFSerializer.cpp:1704
#2  0x00007ffff4641e0b in ModelLoader::load (this=this@entry=0x5555647aa95c, data=..., mapping=..., url=..., webMediaType="") at /home/motofckr9k/Vircadia/source/libraries/model-networking/src/model-networking/ModelLoader.cpp:23
#3  0x00007ffff4636494 in GeometryReader::run (this=0x5555647aa950) at /home/motofckr9k/Vircadia/source/libraries/model-networking/src/model-networking/ModelCache.cpp:158
#4  0x00007fffde04f2aa in QThreadPoolThread::run (this=0x55556e9dc7d0) at /home/motofckr9k/build_qt/qt5/qtbase/src/corelib/thread/qthreadpool.cpp:100
#5  0x00007fffde04b90c in QThreadPrivate::start (arg=0x55556e9dc7d0) at /home/motofckr9k/build_qt/qt5/qtbase/src/corelib/thread/qthread_unix.cpp:329
#6  0x00007ffff6c03669 in start_thread (arg=<optimized out>) at pthread_create.c:479
#7  0x00007fffddb6c2b3 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```
Sentry reports linked to crashing while loading assets in that domain:
https://sentry.vircadia.dev/share/issue/4d7bf3bf4eec47e6b0001677727b967d/
https://sentry.vircadia.dev/share/issue/f2863b3ef4d844c58600242b1917837e/
https://sentry.vircadia.dev/organizations/vircadia/issues/531/?project=2

**Comment by ksuprynowicz** [comment]
This seems to fix the problem for me:
https://github.com/vircadia/vircadia/pull/1545
