### ISSUE TITLE
Running CMake unable to build

### ISSUE THREAD

**Issue by Dragonstormthunder** [vircadia/vircadia#1667]
Running CMake on the vircadia build during step 7 fails to build, i.e. `cmake .. -G "Visual Studio 16 2019" -A x64`

```
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j21
    Working Directory: C:/Users/emmad/Desktop/fb3a0d76/buildtrees/openexr/x64-windows-dbg
    See logs for more information:
      C:\Users\emmad\Desktop\fb3a0d76\buildtrees\openexr\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  ports/openexr/portfile.cmake:33 (vcpkg_install_cmake)
  scripts/ports.cmake:146 (include)


error: building openexr:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openexr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openexr]+Build+error
Include '[openexr] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: 3d8f78171 2022-06-15 (7 hours ago)

You can also use the prefilled template from C:\Users\emmad\Desktop\fb3a0d76\installed\vcpkg\issue_body.md.
Traceback (most recent call last):

  File "C:\Users\emmad\Desktop\Repositories\vircadia\prebuild.py", line 203, in <module>
    main()
  File "C:\Users\emmad\Desktop\Repositories\vircadia\prebuild.py", line 170, in main
    pm.setupDependencies(qt=qtInstallPath)
  File "C:\Users\emmad\Desktop\Repositories\vircadia\hifi_vcpkg.py", line 269, in setupDependencies
    self.run(['install', '--triplet', self.getTripletWithBuildType(self.triplet), 'hifi-client-deps'])
  File "C:\Users\emmad\Desktop\Repositories\vircadia\hifi_vcpkg.py", line 227, in run
    hifi_utils.executeSubprocess(actualCommands, folder=self.path, env=self.buildEnv)
  File "C:\Users\emmad\Desktop\Repositories\vircadia\hifi_utils.py", line 74, in executeSubprocess
    raise RuntimeError('Call to "{}" failed.\n\narguments:\n{}\n'.format(
RuntimeError: Call to "C:\Users\emmad\Desktop\fb3a0d76\vcpkg.exe" failed.

arguments:
--vcpkg-root C:\Users\emmad\Desktop\fb3a0d76 install --triplet x64-windows hifi-client-deps

CMake Error at CMakeLists.txt:151 (message):
  prebuild.py failed with error 1


-- Configuring incomplete, errors occurred!
```

Only VS2019 installed on machine (environment variable has been configured).
CMake used is 3.23.2.

Log:
[install-x64-windows-dbg-out.log](https://github.com/vircadia/vircadia/files/8915857/install-x64-windows-dbg-out.log)

**Comment by namark** [comment]
I believe this has been resolved by re-running the build with the `HIFI_VCPKG_BASE` environment variable unset. Was either an issue with the specific directory or some kind of a file system fluke.

**Comment by Dragonstormthunder** [comment]
Yep, it has been. Removing the `HIFI_VCPKG_BASE` fixed it. Thanks again!
