### ISSUE TITLE
Crash when running VR in apitrace on Linux

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#810]
When running the Interface in VR mode on Linux inside apitrace, it crashes.
Here is gdb output of the problem:
```
#0  0x00007fffeda289c4 in hifi::qml::OffscreenSurface::getRootItem() (this=0x0) at /home/motofckr9k/Vircadia/source/libraries/qml/src/qml/OffscreenSurface.cpp:120
#1  0x00007fffeebf1366 in OffscreenUi::isVisible(QString const&) (this=0x0, name=...) at /home/motofckr9k/Vircadia/source/libraries/ui/src/OffscreenUi.cpp:229
#2  0x00007fffeec34b3c in TabletProxy::setToolbarMode(bool) (this=0x555568275e20, toolbarMode=false) at /home/motofckr9k/Vircadia/source/libraries/ui/src/ui/TabletScriptingInterface.cpp:392
#3  0x00007fffeec331fe in TabletScriptingInterface::setToolbarMode(bool) (this=0x5555570b9c90, toolbarMode=false) at /home/motofckr9k/Vircadia/source/libraries/ui/src/ui/TabletScriptingInterface.cpp:224
#4  0x0000555555b0b5c4 in Application::updateSystemTabletMode() (this=0x7fffffffae10) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9371
#5  0x0000555555bc3170 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Application::*)()>::call(void (Application::*)(), Application*, void**) (f=(void (Application::*)(Application * const)) 0x555555b0b4ca <Application::updateSystemTabletMode()>, o=0x7fffffffae10, arg=0x7fffffff9fa0) at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#6  0x0000555555bb5cc6 in QtPrivate::FunctionPointer<void (Application::*)()>::call<QtPrivate::List<>, void>(void (Application::*)(), Application*, void**) (f=(void (Application::*)(Application * const)) 0x555555b0b4ca <Application::updateSystemTabletMode()>, o=0x7fffffffae10, arg=0x7fffffff9fa0)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#7  0x0000555555b9e6ee in QtPrivate::QSlotObject<void (Application::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x5555571afe60, r=0x7fffffffae10, a=0x7fffffff9fa0, ret=0x0)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:414
#8  0x00007fffea86785f in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#9  0x00005555560d5287 in Application::activeDisplayPluginChanged() (this=0x7fffffffae10) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/UVLADIE3JM/moc_Application.cpp:1027
#10 0x0000555555b08837 in Application::setDisplayPlugin(std::shared_ptr<DisplayPlugin>) (this=0x7fffffffae10, newDisplayPlugin=std::shared_ptr<DisplayPlugin> (use count 7, weak count 0) = {...}) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9010
#11 0x0000555555b0ac30 in Application::setActiveDisplayPlugin(QString const&) (this=0x7fffffffae10, pluginName=...) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9282
#12 0x0000555555b08dbc in Application::switchDisplayMode() (this=0x7fffffffae10) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:9046
#13 0x00005555560d4240 in Application::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x7fffffffae10, _c=QMetaObject::InvokeMetaMethod, _id=129, _a=0x7fffffffa560) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/UVLADIE3JM/moc_Application.cpp:804
#14 0x00007fffea867745 in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#15 0x00007fffea874627 in QTimer::timeout(QTimer::QPrivateSignal) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#16 0x00007fffea874988 in QTimer::timerEvent(QTimerEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#17 0x00007fffea86826b in QObject::event(QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#18 0x00007fffeb31ae6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Widgets.so.5
#19 0x00007fffeb322450 in QApplication::notify(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Widgets.so.5
#20 0x0000555555ae155d in Application::notify(QObject*, QEvent*) (this=0x7fffffffae10, object=0x55555b598d70, event=0x7fffffffa950) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4209
#21 0x00007fffea837b48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#22 0x00007fffea8940e9 in QTimerInfoList::activateTimers() () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#23 0x00007fffea8948e9 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#24 0x00007fffe09ff417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007fffe09ff650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007fffe09ff6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007fffea894c7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#28 0x00007fffea835d9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#29 0x00007fffea83efa0 in QCoreApplication::exec() () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#30 0x0000555555df26d3 in main(int, char const**) (argc=1, argv=0x7fffffffdb98) at /home/motofckr9k/Vircadia/source/interface/src/main.cpp:445
```
And a strace: 
[strace_vrtest.log.zip](https://github.com/kasenvr/project-athena/files/5374197/strace_vrtest.log.zip)

@HifiExperiments worked around this issue by doing:
```
diff --git a/libraries/ui/src/ui/TabletScriptingInterface.cpp b/libraries/ui/src/ui/TabletScriptingInterface.cpp
index 040bb750d08..c2fe38eae2d 100644
--- a/libraries/ui/src/ui/TabletScriptingInterface.cpp
+++ b/libraries/ui/src/ui/TabletScriptingInterface.cpp
@@ -385,6 +385,7 @@ void TabletProxy::setToolbarMode(bool toolbarMode) {
         connect(tabletRootWindow, &QmlWindowClass::fromQml, this, &TabletProxy::fromQml);
 #endif
     } else {
+#if !defined(DISABLE_QML)
         if (_currentPathLoaded != TABLET_HOME_SOURCE_URL) {
             loadHomeScreen(true);
         }
@@ -395,6 +396,7 @@ void TabletProxy::setToolbarMode(bool toolbarMode) {
         }

         offscreenUi->hideDesktopWindows();
+#endif
         // destroy desktop window
         if (_desktopWindow) {
             _desktopWindow->deleteLater();
```

**Comment by daleglass** [comment]
Probably related to #809, QML looks like it needs disabling

**Comment by JulianGro** [comment]
This crash happens after building without QML. So just disabling QML at build doesn't fix this.
