### ISSUE TITLE
Another crash when running VR in apitrace on Linux

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#811]
After applying the patch from https://github.com/kasenvr/project-athena/issues/810, we crash again at a later point.
gdb output:
```
#0  0x00007fffeebf10c4 in OffscreenUi::isPointOnDesktopWindow(QVariant) (this=0x0, point=...) at /home/motofckr9k/Vircadia/source/libraries/ui/src/OffscreenUi.cpp:212
#1  0x0000555555f3eecf in WindowScriptingInterface::isPointOnDesktopWindow(QVariant) (this=0x555559338340, point=...) at /home/motofckr9k/Vircadia/source/interface/src/scripting/WindowScriptingInterface.cpp:204
#2  0x00005555560f9a4f in WindowScriptingInterface::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x555559338340, _c=QMetaObject::InvokeMetaMethod, _id=86, _a=0x7ffe8e940970) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/SZBG4JW7DO/moc_WindowScriptingInterface.cpp:560
#3  0x00005555560fb43b in WindowScriptingInterface::qt_metacall(QMetaObject::Call, int, void**) (this=0x555559338340, _c=QMetaObject::InvokeMetaMethod, _id=86, _a=0x7ffe8e940970) at /home/motofckr9k/Vircadia/build/interface/interface_autogen/SZBG4JW7DO/moc_WindowScriptingInterface.cpp:797
#4  0x00007fffebbcac8a in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#5  0x00007fffebbc47e7 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#6  0x00007fffebbc527e in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#7  0x00007fffebbc54b2 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#8  0x00007fffebad1028 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#9  0x00007fffebaa77f5 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#10 0x00007fff0425aea0 in  ()
#11 0x00007ffe8e940f40 in  ()
#12 0x00007ffe66487f40 in  ()
#13 0x00007ffe00000010 in  ()
#14 0x7ff9000000000002 in  ()
#15 0x00007ffd00000003 in  ()
#16 0x0000555500000010 in  ()
#17 0x00007ffe8e940f60 in  ()
#18 0x0000555555b76a74 in QSharedPointer<ScriptEngines>::deref() (this=0x7fffebc42dc8) at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qsharedpointer_impl.h:460
#19 0x00007fffeba5e779 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#20 0x00007fffebaf9b5d in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#21 0x00007fffebbb2919 in QScriptValue::call(QScriptValue const&, QList<QScriptValue> const&) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#22 0x00007ffff3f37146 in ScriptEngine::<lambda()>::operator()(void) const (__closure=0x55556ed595b0) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2712
#23 0x00007ffff3f3b044 in std::_Function_handler<void(), ScriptEngine::callWithEnvironment(const EntityItemID&, const QUrl&, QScriptValue, QScriptValue, QScriptValueList)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...) at /usr/include/c++/7/bits/std_function.h:316
#24 0x0000555555b3f2ba in std::function<void ()>::operator()() const (this=0x7ffe8e9412c0) at /usr/include/c++/7/bits/std_function.h:706
#25 0x00007ffff3f3702d in ScriptEngine::doWithEnvironment(EntityItemID const&, QUrl const&, std::function<void ()>) (this=0x55556d87ef80, entityID=..., sandboxURL=..., operation=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2703
#26 0x00007ffff3f371f6 in ScriptEngine::callWithEnvironment(EntityItemID const&, QUrl const&, QScriptValue, QScriptValue, QList<QScriptValue>) (this=0x55556d87ef80, entityID=..., sandboxURL=..., function=..., thisObject=..., args=...)
    at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2714
#27 0x00007ffff3f286eb in ScriptEngine::timerFired() (this=0x55556d87ef80) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:1473
#28 0x00007ffff3f6224a in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (ScriptEngine::*)()>::call(void (ScriptEngine::*)(), ScriptEngine*, void**) (f=(void (ScriptEngine::*)(ScriptEngine * const)) 0x7ffff3f2847a <ScriptEngine::timerFired()>, o=0x55556d87ef80, arg=0x7ffe8e941590)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#29 0x00007ffff3f5e732 in QtPrivate::FunctionPointer<void (ScriptEngine::*)()>::call<QtPrivate::List<>, void>(void (ScriptEngine::*)(), ScriptEngine*, void**) (f=(void (ScriptEngine::*)(ScriptEngine * const)) 0x7ffff3f2847a <ScriptEngine::timerFired()>, o=0x55556d87ef80, arg=0x7ffe8e941590)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#30 0x00007ffff3f58e96 in QtPrivate::QSlotObject<void (ScriptEngine::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x7ffdf4074130, r=0x55556d87ef80, a=0x7ffe8e941590, ret=0x0)
    at /home/motofckr9k/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:414
#31 0x00007fffea86785f in QMetaObject::activate(QObject*, int, int, void**) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#32 0x00007fffea874627 in QTimer::timeout(QTimer::QPrivateSignal) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#33 0x00007fffea874988 in QTimer::timerEvent(QTimerEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#34 0x00007fffea86826b in QObject::event(QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#35 0x00007fffeb31ae6c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Widgets.so.5
#36 0x00007fffeb322450 in QApplication::notify(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Widgets.so.5
#37 0x0000555555ae1584 in Application::notify(QObject*, QEvent*) (this=0x7fffffffaed0, object=0x7ffdf405d350, event=0x7ffe8e941980) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4212
#38 0x00007fffea837b48 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#39 0x00007fffea8940e9 in QTimerInfoList::activateTimers() () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#40 0x00007fffea8948b1 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#41 0x00007fffe09ff417 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x00007fffe09ff650 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x00007fffe09ff6dc in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x00007fffea894c7f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#45 0x00007fffea835d9a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Core.so.5
#46 0x00007ffff3f307a0 in ScriptEngine::include(QStringList const&, QScriptValue) (this=0x55556d87ef80, includeFiles=..., callback=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2039
#47 0x00007ffff3f30c4c in ScriptEngine::include(QString const&, QScriptValue) (this=0x55556d87ef80, includeFile=..., callback=...) at /home/motofckr9k/Vircadia/source/libraries/script-engine/src/ScriptEngine.cpp:2053
#48 0x00007ffff3fad80b in ScriptEngine::qt_static_metacall(QObject*, QMetaObject::Call, int, void**) (_o=0x55556d87ef80, _c=QMetaObject::InvokeMetaMethod, _id=44, _a=0x7ffe8e9420e0) at /home/motofckr9k/Vircadia/build/libraries/script-engine/script-engine_autogen/UVLADIE3JM/moc_ScriptEngine.cpp:474
#49 0x00007ffff3faf293 in ScriptEngine::qt_metacall(QMetaObject::Call, int, void**) (this=0x55556d87ef80, _c=QMetaObject::InvokeMetaMethod, _id=44, _a=0x7ffe8e9420e0) at /home/motofckr9k/Vircadia/build/libraries/script-engine/script-engine_autogen/UVLADIE3JM/moc_ScriptEngine.cpp:817
#50 0x00007fffebbcac8a in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#51 0x00007fffebbc47e7 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#52 0x00007fffebbc527e in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#53 0x00007fffebbc54b2 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#54 0x00007fffebad1028 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#55 0x00007fffebaa77f5 in  () at /home/motofckr9k/Vircadia/qt5-install/lib/libQt5Script.so.5
#56 0x00007fff0413405b in  ()
#57 0x0000000000000003 in  ()
#58 0x00007fff013869c0 in  ()
#59 0x00007fff00000011 in  ()
#60 0x00007fff00000002 in  ()
#61 0x00007ffe8e9426e0 in  ()
#62 0x00007ffe995bf9b0 in  ()
#63 0x00007ffe995da540 in  ()
#64 0x0000000000000000 in  ()
```
And a strace: 
[strace_vrtest_test1.log.zip](https://github.com/kasenvr/project-athena/files/5374244/strace_vrtest_test1.log.zip)

@HifiExperiments worked around the issue by doing:
```
diff --git a/libraries/ui/src/OffscreenUi.cpp b/libraries/ui/src/OffscreenUi.cpp
index 34184057e07..501ff519e24 100644
--- a/libraries/ui/src/OffscreenUi.cpp
+++ b/libraries/ui/src/OffscreenUi.cpp
@@ -208,6 +208,7 @@ void OffscreenUi::toggle(const QUrl& url, const QString& name, std::function<voi
 }

 bool OffscreenUi::isPointOnDesktopWindow(QVariant point) {
+    return false;
     QVariant result;
     BLOCKING_INVOKE_METHOD(_desktop, "isPointOnWindow",
                            Q_RETURN_ARG(QVariant, result),
@@ -226,12 +227,14 @@ void OffscreenUi::hide(const QString& name) {
 }
```

**Comment by daleglass** [comment]
Probably related to #809, QML looks like it needs disabling
