### ISSUE TITLE
Generating build file on Windows 10 failes with "Error: Building package glslang:x64-windows failed with: BUILD_FAILED"

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#911]
Trying to generate build files according to https://github.com/vircadia/vircadia/blob/master/BUILD_WIN.md fails with:
```
C:\Users\MotoFckr9k\Downloads\vircadia\build>cmake .. -G "Visual Studio 16 2019" -A x64
-- EXTERNAL_BUILD_ASSETS: https://athena-public.s3.amazonaws.com
-- Found Python3: C:/Program Files/Python39/python.exe (found version "3.9.1") found components:  Interpreter
Using the Python interpreter located at: C:/Program Files/Python39/python.exe
['C:/Users/MotoFckr9k/Downloads/vircadia/prebuild.py', '--release-type', 'DEV', '--build-root', 'C:/Users/MotoFckr9k/Downloads/vircadia/build']
Using qt path C:\Users\MotoFckr9k/hifi/qt\5.12.3
Qt has already been downloaded
Writing cmake config to C:/Users/MotoFckr9k/Downloads/vircadia/build\qt.cmake
Using vcpkg path C:\Users\MotoFckr9k/hifi/vcpkg\237d1950
Exe file C:\Users\MotoFckr9k/hifi/vcpkg\237d1950\vcpkg.exe not found, out of date
Exe file C:\Users\MotoFckr9k/hifi/vcpkg\237d1950\vcpkg.exe not found, out of date
Cleaning vcpkg installation at C:\Users\MotoFckr9k/hifi/vcpkg\237d1950
Missing executable, boot-strapping
Cloning vcpkg from github to C:\Users\MotoFckr9k/hifi/vcpkg\237d1950
Cloning into 'C:\Users\MotoFckr9k/hifi/vcpkg\237d1950'...
Updating files: 100% (5676/5676), done.
Bootstrapping vcpkg

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  xmlserializer.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.fetch.cpp
  commands.format-manifest.cpp
  commands.hash.cpp
  commands.info.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.upload-metrics.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  configuration.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.ifw.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  registries.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiondeserializers.cpp
  versions.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkg.cpp
  Code wird generiert.
  Previous IPDB not found, fall back to full compilation.
  All 22914 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Codegenerierung ist abgeschlossen.
  vcpkg.vcxproj -> C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\toolsrc\windows-bootstrap\msbuild.x86.release\vcpkg.exe

Building vcpkg.exe... done.

Replacing port files
Passing on variables to vcpkg
Writing tag 237d1950_1 to C:\Users\MotoFckr9k/hifi/vcpkg\237d1950\.id
Installing host tools
Running command
['C:\\Users\\MotoFckr9k/hifi/vcpkg\\237d1950\\vcpkg.exe', '--vcpkg-root', 'C:\\Users\\MotoFckr9k/hifi/vcpkg\\237d1950', 'install', '--triplet', 'x64-windows', 'hifi-host-tools']
Computing installation plan...
A suitable version of cmake was not found (required v3.18.4). Downloading portable cmake v3.18.4...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4-win32-x86.zip -> C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\downloads\cmake-3.18.4-win32-x86.zip
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\downloads\7-zip.commandline.18.1.0.nupkg
Extracting 7zip...
A suitable version of nuget was not found (required v5.5.1). Downloading portable nuget v5.5.1...
Downloading nuget...
  https://dist.nuget.org/win-x86-commandline/v5.5.1/nuget.exe -> C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\downloads\22ea847d-nuget.exe
The following packages will be built and installed:
  * glslang[core]:x64-windows -> untagged-048c4dbc7f021224a933-1
    hifi-host-tools[core]:x64-windows -> 0
  * hifi-scribe[core]:x64-windows -> 1bd638a36ca771e5a68d01985b6389b71835cbd2
  * spirv-cross[core]:x64-windows -> 2018-08-07-1
  * spirv-tools[core]:x64-windows -> 2018.5-1
Additional packages (*) will be modified to complete this operation.
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
Please install the English language pack.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.0.3). Downloading portable powershell-core v7.0.3...
Downloading powershell-core...
  https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/PowerShell-7.0.3-win-x86.zip -> C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\downloads\PowerShell-7.0.3-win-x86.zip
Extracting powershell-core...
Could not locate cached archive: C:\Users\MotoFckr9k\AppData\Local\vcpkg\archives\e6\e6c0687eb50a823750092020c2e7130619ecf8f6.zip
Could not locate cached archive: C:\Users\MotoFckr9k\AppData\Local\vcpkg\archives\34\34da310d207265f7dd4e2e2c0cb39b880e4721e3.zip
Could not locate cached archive: C:\Users\MotoFckr9k\AppData\Local\vcpkg\archives\8c\8cb4d465c9ecf5a1d2229fcec0143a8b3ff042bd.zip
Could not locate cached archive: C:\Users\MotoFckr9k\AppData\Local\vcpkg\archives\c5\c5e39a46a4e91ee77cc9de6e9a278588bf5b01db.zip
Could not locate cached archive: C:\Users\MotoFckr9k\AppData\Local\vcpkg\archives\84\8469086127cbf0c68ff1745da5841b7c6675e30f.zip
Starting package 1/5: glslang:x64-windows
Building package glslang[core]:x64-windows...
CMake Warning at scripts/cmake/vcpkg_common_functions.cmake:3 (message):
  vcpkg_common_functions has been removed and all values are automatically
  provided in all portfile.cmake invocations.  Please remove
  `include(vcpkg_common_functions)`.
Call Stack (most recent call first):
  ports/glslang/portfile.cmake:1 (include)
  scripts/ports.cmake:136 (include)


-- Note: glslang only supports static library linkage. Building static library.
-- Downloading https://github.com/KhronosGroup/glslang/archive/untagged-048c4dbc7f021224a933.tar.gz...
-- Extracting source C:/Users/MotoFckr9k/hifi/vcpkg/237d1950/downloads/KhronosGroup-glslang-untagged-048c4dbc7f021224a933.tar.gz
-- Using source at C:/Users/MotoFckr9k/hifi/vcpkg/237d1950/buildtrees/glslang/src/021224a933-e13bc399d3.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/MotoFckr9k/hifi/vcpkg/237d1950/buildtrees/glslang/x64Traceback (most recent call last):
-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\buildtrees\glslang\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/glslang/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package glslang:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glslang:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
  File "C:\Users\MotoFckr9k\Downloads\vircadia\prebuild.py", line 200, in <module>
    main()
  File "C:\Users\MotoFckr9k\Downloads\vircadia\prebuild.py", line 168, in main
    pm.setupDependencies(qt=qtInstallPath)
  File "C:\Users\MotoFckr9k\Downloads\vircadia\hifi_vcpkg.py", line 251, in setupDependencies
    self.run(['install', '--triplet', self.getTripletWithBuildType(self.hostTriplet), 'hifi-host-tools'])
  File "C:\Users\MotoFckr9k\Downloads\vircadia\hifi_vcpkg.py", line 216, in run
    hifi_utils.executeSubprocess(actualCommands, folder=self.path, env=self.buildEnv)
  File "C:\Users\MotoFckr9k\Downloads\vircadia\hifi_utils.py", line 62, in executeSubprocess
    raise RuntimeError('Call to "{}" failed.\n\narguments:\n{}\n'.format(
RuntimeError: Call to "C:\Users\MotoFckr9k/hifi/vcpkg\237d1950\vcpkg.exe" failed.

arguments:
--vcpkg-root C:\Users\MotoFckr9k/hifi/vcpkg\237d1950 install --triplet x64-windows hifi-host-tools

CMake Error at CMakeLists.txt:85 (message):
  vcpkg configuration missing.


-- Configuring incomplete, errors occurred!

C:\Users\MotoFckr9k\Downloads\vircadia\build>
```

Microsoft does give easy access to Windows 10 nowadays, so if anyone want to try troubleshoot this they could just run a VM with https://www.microsoft.com/en-us/software-download/windows10ISO

**Comment by ctrlaltdavid** [comment]
1) Are you running the cmake command in a "Developer Command Prompt for VS 2019" command window? (You can find this version of a command window in the Start menu in the "Visual Studio 2019" folder.
2) If you type the command, `where ninja` it should report if / where it finds the `ninja` program.

**Comment by JulianGro** [comment]
I have been using the normal command prompt as in the instructions. Using the VS 2019 Developer Command Prompt didn't change anything.

Ninja is installed apparently:
```
C:\Users\MotoFckr9k\Downloads\vircadia\build>where ninja
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe

C:\Users\MotoFckr9k\Downloads\vircadia\build>
```

**Comment by ctrlaltdavid** [comment]
The Windows build instructions should be tested using a fresh Windows 10 such as provided in a Windows 10 VM: windows 10 isos nowadays: https://www.microsoft.com/en-us/software-download/windows10ISO

**Comment by JulianGro** [comment]
This seems to have been a mixture of the english language packs missing and something else.
I will leave this open as the build docs will need an update.

**Comment by daleglass** [comment]
Is this still happening? 

The log above says the actual problem should be logged in `C:\Users\MotoFckr9k\hifi\vcpkg\237d1950\buildtrees\glslang\config-x64-windows-out.log`

**Comment by JulianGro** [comment]
I don't do Windows builds so I am going to close this issue for now.
