### ISSUE TITLE
Cannot generate build file on Windows 10 without git repository

### ISSUE THREAD

**Issue by JulianGro** [vircadia/vircadia#912]
Trying to generate build files according to https://github.com/vircadia/vircadia/blob/master/BUILD_WIN.md fails if you provide it with the source downloaded from github directly rather than cloning it with `git clone`:
```
C:\Users\MotoFckr9k\Downloads\vircadia-master\build>cmake .. -G "Visual Studio 16 2019" -A x64
-- EXTERNAL_BUILD_ASSETS: https://athena-public.s3.amazonaws.com
-- Found Python3: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe (found version "3.7.8") found components:  Interpreter
Using the Python interpreter located at: C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/python.exe
['C:/Users/MotoFckr9k/Downloads/vircadia-master/prebuild.py', '--release-type', 'DEV', '--build-root', 'C:/Users/MotoFckr9k/Downloads/vircadia-master/build']
C:/Users/MotoFckr9k/Downloads/vircadia-master/prebuild.py:63: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn("Unable to find git executable, can't caclulate commit ID")
Unable to find git executable, can't caclulate commit ID
Using qt path C:\Users\MotoFckr9k/hifi/qt\5.12.3
Downloading Qt from AWS
Extracting https://athena-public.s3.amazonaws.com/dependencies/vcpkg/qt5-install-5.12.3-windows3.tar.gz%3FversionId=5ADqP0M0j5ZfimUHrx4zJld6vYceHEsI to C:\Users\MotoFckr9k/hifi/qt\5.12.3
Writing cmake config to C:/Users/MotoFckr9k/Downloads/vircadia-master/build\qt.cmake
Using vcpkg path C:\Users\MotoFckr9k/hifi/vcpkg\237d1950
Exe file C:\Users\MotoFckr9k/hifi/vcpkg\237d1950\vcpkg.exe not found, out of date
Exe file C:\Users\MotoFckr9k/hifi/vcpkg\237d1950\vcpkg.exe not found, out of date
Cleaning vcpkg installation at C:\Users\MotoFckr9k/hifi/vcpkg\237d1950
Missing executable, boot-strapping
Cloning vcpkg from github to C:\Users\MotoFckr9k/hifi/vcpkg\237d1950
Traceback (most recent call last):
  File "C:/Users/MotoFckr9k/Downloads/vircadia-master/prebuild.py", line 200, in <module>
    main()
  File "C:/Users/MotoFckr9k/Downloads/vircadia-master/prebuild.py", line 157, in main
    pm.bootstrap()
  File "C:\Users\MotoFckr9k\Downloads\vircadia-master\hifi_vcpkg.py", line 195, in bootstrap
    hifi_utils.executeSubprocess(['git', 'clone', 'https://github.com/microsoft/vcpkg', self.path])
  File "C:\Users\MotoFckr9k\Downloads\vircadia-master\hifi_utils.py", line 58, in executeSubprocess
    processArgs, stdout=sys.stdout, stderr=sys.stderr, env=env)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
CMake Error at CMakeLists.txt:85 (message):
  vcpkg configuration missing.


-- Configuring incomplete, errors occurred!

C:\Users\MotoFckr9k\Downloads\vircadia-master\build>
```

**Comment by daleglass** [comment]
It looks like git itself isn't being found?

**Comment by daleglass** [comment]
still a thing? Also this looks like git not being installed or in PATH. So maybe it could use a friendlier error message, but doesn't seem to be a bug.

**Comment by JulianGro** [comment]
I am going to close this issue since I don't really want to do any troubleshooting on Windows and no one else seems to have ever encountered it.
